baseURL: /
languageCode: en-us
title: Cossidae Template
summaryLength: 30
disableKinds:
  - taxonomyTerm
markup:
  highlight:
    noClasses: false
  # ensures html inside markdown is allowed to render
  goldmark:
    renderer:
      unsafe: true
module:
  imports:
    - path: github.com/cloudcannon/cossidae
